node_exporter_version: "1.7.0"
node_exporter_filename: "node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
node_exporter_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/{{ node_exporter_filename }}"

loki_version: "2.9.3"
loki_url: "https://github.com/grafana/loki/releases/download/v{{ loki_version }}/loki-linux-amd64.zip"

promtail_version: "2.9.3"
promtail_url: "https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/promtail-linux-amd64.zip"

# Monitor server hosts metrics + logs (brain) and blackbox (probe)
prometheus_server: "{{ hostvars[groups['monitoring'][0]].ansible_host }}"
loki_server: "{{ hostvars[groups['monitoring'][0]].ansible_host }}"

# Application Repository URLs (defined in secrets.yml)
mek_lab_backend_repo_url: "{{ vault_mek_lab_backend_repo_url }}"
geoserver_repo_url: "{{ vault_geoserver_repo_url }}"
meklab_llm_repo_url: "{{ vault_meklab_llm_repo_url }}"
salome_repo_url: "{{ vault_salome_repo_url }}"